name       : python-editables
version    : 0.3
release    : 1
source     :
    - https://github.com/pfmoore/editables/archive/refs/tags/0.3.tar.gz : 42f7240164af1e028ccb7b60e72f54bbd8b639e9409595fbeffac5d3fb610643
homepage   : https://github.com/pfmoore/editables
license    : MIT
component  : programming.python
summary    : A Python library for creating "editable wheels"
description: |
    This library supports the building of wheels which, when installed, will expose packages in a local directory on sys.path in "editable mode". In other words, changes to the package source will be reflected in the package visible to Python, without needing a reinstall.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
